### ISSUE TITLE
Add local domain name to PHP /etc/hosts file

### ISSUE THREAD

**Issue by hiberus-magento** [hiberus-magento/hiberus-dockergento#110]
During project installation, modify file `/etc/hosts` of PHP container for including a reference to Hitch container IP.

**Comment by dabad-es** [comment]
Use `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' XXXXX`  for getting Hitch container IP address and add it to /etc/hosts in PHP container.

**Comment by dabad-es** [comment]
Copy local CA certificate to  PHP container:
`docker cp /usr/local/share/ca-certificates/[...].crt [...]_phpfpm_1:/usr/local/share/ca-certificates/[...].crt
`
And refresh certificates (as root):
`update-ca-certificates`
