### ISSUE TITLE
Docker is not properly configured or docker is not runnig. Please execute: hm setup.

### ISSUE THREAD

**Issue by RusDovOnilab** [hiberus-magento/hiberus-dockergento#87]
<img width="987" alt="image" src="https://user-images.githubusercontent.com/17047093/190508716-d09899af-2c7f-4275-9a65-3f200a2c6b4b.png">
It looks like a joke, but the project did not start :)

**Comment by sergiomfg** [comment]
Thank you @RusDovOnilab. We had detected this bug and we are working to fix it.
We will try to fix it as soon as possible.
